### PR TITLE
perf(api): let a world prove it is unchanged for one document

### PR DESCRIPTION
**Pull request by gtanczyk**
## Why

Shared worlds were the last unbounded read on the platform, and the largest single cost risk
left after [#1143](https://github.com/gamedevpl/www.gamedev.pl/pull/1143) and
[#1154](https://github.com/gamedevpl/www.gamedev.pl/pull/1154).

The cache added in #1154 bounds how *often* `GET /api/games/:slug/world` reads Firestore — 3s
per world, single-flighted — but every miss still reads the **entire** collection, and a world
caps at `MAX_WORLD_ENTRIES = 2000`. The cadence belongs to game code, not to the shell: the
bridge reads only when the game sends `commons:hello` or `commons:list`. So one popular game
with a world, polled through the day, costs:

| World size | Reads/day | ≈ $/month, one game |
|---|---|---|
| 50 entries | 1.4M | $13 |
| 200 entries | 5.8M | $54 |
| 2000 entries (the cap) | 57.6M | $536 |

$54/month for a single game is more than the entire rest of the site costs today. The threshold
was never a user count — it was **the first world people actually play in all day**.

## What changed

Every write to a world bumps a `rev` counter on the world document, **in the same transaction as
the entry**, so a reader can never observe one without the other. A read whose window has lapsed
then asks for that one document instead of the collection: if `rev` has not moved, the snapshot
already held is provably current and nothing else is read.

At 200 entries that turns ~5.8M reads/day into **~86K** — the 28.8K revision checks a maxed-out
client can force, plus the periodic full re-reads below. Roughly 67× cheaper, and ~95× at the cap,
where the saving matters most.

The revision is read-modify-write inside the transaction rather than a `FieldValue.increment`
sentinel. That is deliberate: the fake Firestore does not implement `FieldValue`, so a sentinel
would have left this path untested against anything but production. Both backends now run the
same parity suite.

**Two things still deliberately cost a full read:**

- **Any write invalidates its world outright**, so a player never waits out a window to see their
  own change. Unchanged from #1154.
- **A snapshot is re-read whole every five minutes** regardless of the revision. This bounds what
  a change that skipped the counter — a console edit, a migration script — can hide, and drops
  worlds nobody is playing out of memory.

## Verification

- `npm run lint` — clean
- `npm test` — all suites green (3,724 API / 1,937 web / 106 contract / 104 zone-core / 20 world).
  One known flake in `agent-channel.test.ts` under full-suite load; passes in isolation and is
  untouched by this branch.
- New `world-entries.test.ts` runs the revision contract against **both** the in-memory and
  Firestore stores via `describe.each`: it moves on claim, edit, delete and erasure; it holds
  still for a refused write (a conflict must not read as a change); and one world's revision
  never leaks into another.
- `worlds.test.ts` gains coverage for the three route behaviours: an unchanged world costs one
  document and zero collection reads, a moved revision forces a re-read (written straight to the
  store, so route-level invalidation cannot explain the result), and the five-minute ceiling
  re-reads even when nothing bumped the counter.

## Not in this PR

Round hygiene — 39 open rounds across 13 users, because `needs_changes` and `failed` never close.
The notify sweep is `O(open rounds)` and sequential, so it stops fitting its 2-minute window at
roughly 500 rounds. That is the platform's remaining hard limit, and it wants its own change.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by gtanczyk** [comment]
@codex

File: apps/api/src/store/slices/world-entries.ts [hunk 1]
```diff
@@ -182,22 +215,34 @@ export class FirestoreWorldEntriesStore implements WorldEntriesStore {
         createdAt: entry.createdAt,
         updatedAt: entry.updatedAt,
       });
+      // Same transaction, so no reader sees one without the other.
+      tx.set(worldRef, { rev: this.revisionOf(worldSnap.data()) + 1 }, { merge: true });
```
[the remark this answers is not in the document]
Comment (gtanczyk) [reply apps/api/src/store/slices/world-entries.ts]: Fixed in 52e288c2: the revision is now a set of shard documents under the world, and a write stamps one of them at random with a per-write unique value — no read of a shared document inside the entry transaction, so writers contend only on a shard, not on the world. The reader compares the joined vector of stamps; eight reads per check instead of one, still far under the collection.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_

File: apps/api/src/store/slices/world-entries.ts [hunk 2]
```diff
@@ -228,6 +273,9 @@ export class FirestoreWorldEntriesStore implements WorldEntriesStore {
       for (const doc of snap.docs.slice(index, index + 400)) batch.delete(doc.ref);
       await batch.commit();
     }
+    // Else an erased world serves the removed rows from cache.
+    const worlds = new Set(snap.docs.map((doc) => doc.ref.parent.parent?.id).filter(Boolean) as string[]);
+    for (const worldId of worlds) await this.bumpRevision(worldId);
```
[the remark this answers is not in the document]
Comment (gtanczyk) [reply apps/api/src/store/slices/world-entries.ts]: Fixed in 52e288c2: the stamp now rides in the same batch as the deletes it invalidates, one per world touched by that batch, so the rows and the token that retires them commit together or not at all. No separate bump step left to lose.

_🤖 Addressed by [Claude Code](https://claude.com/claude-code)_
